# -*- coding: utf-8 -*-
"""Ag-news.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1riTTAelEi9Yd5cuurZEOOhawVTppshnl

#Install Dependencies
"""

!jupyter notebook --clear-cache

!pip uninstall nltk -y
!pip install nltk
!pip install -U nltk

"""#Import libraries  """

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTE
import string
import string
string.punctuation
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
# Import PorterStemmer from NLTK Library
from nltk.stem.porter import PorterStemmer
import nltk
import warnings
warnings.filterwarnings('ignore')
from nltk.corpus import stopwords

# Download required NLTK data
nltk.download('stopwords')
nltk.download('punkt_tab')
nltk.download('wordnet')
nltk.download('omw-1.4')

import kagglehub

# Download latest version
path = kagglehub.dataset_download("amananandrai/ag-news-classification-dataset")

print("Path to dataset files:", path)

data = pd.read_csv(f'{path}/train.csv', header=None)
data = data.iloc[1:].copy()

data.columns = ['Class Index', 'Title', 'Description']
data['text'] = data['Title'].str.lower() + " " + data['Description'].str.lower()

data.head()

data.isnull().sum()

data['Class Index'].value_counts()

"""#Data Preprocessing"""

# Function to remove HTML Tags
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

# Here We also Use Regular Expressions to Remove URLs from Text or Whole Corpus.
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

punc = string.punctuation

def remove_punc(text):
    return text.translate(str.maketrans('', '', punc))

# Here Come ChatWords Which i Get from a Github Repository
# Repository Link : https://github.com/rishabhverma17/sms_slang_translator/blob/master/slang.txt
chat_words = {
    "AFAIK": "As Far As I Know",
    "AFK": "Away From Keyboard",
    "ASAP": "As Soon As Possible",
    "ATK": "At The Keyboard",
    "ATM": "At The Moment",
    "A3": "Anytime, Anywhere, Anyplace",
    "BAK": "Back At Keyboard",
    "BBL": "Be Back Later",
    "BBS": "Be Back Soon",
    "BFN": "Bye For Now",
    "B4N": "Bye For Now",
    "BRB": "Be Right Back",
    "BRT": "Be Right There",
    "BTW": "By The Way",
    "B4": "Before",
    "B4N": "Bye For Now",
    "CU": "See You",
    "CUL8R": "See You Later",
    "CYA": "See You",
    "FAQ": "Frequently Asked Questions",
    "FC": "Fingers Crossed",
    "FWIW": "For What It's Worth",
    "FYI": "For Your Information",
    "GAL": "Get A Life",
    "GG": "Good Game",
    "GN": "Good Night",
    "GMTA": "Great Minds Think Alike",
    "GR8": "Great!",
    "G9": "Genius",
    "IC": "I See",
    "ICQ": "I Seek you (also a chat program)",
    "ILU": "ILU: I Love You",
    "IMHO": "In My Honest/Humble Opinion",
    "IMO": "In My Opinion",
    "IOW": "In Other Words",
    "IRL": "In Real Life",
    "KISS": "Keep It Simple, Stupid",
    "LDR": "Long Distance Relationship",
    "LMAO": "Laugh My A.. Off",
    "LOL": "Laughing Out Loud",
    "LTNS": "Long Time No See",
    "L8R": "Later",
    "MTE": "My Thoughts Exactly",
    "M8": "Mate",
    "NRN": "No Reply Necessary",
    "OIC": "Oh I See",
    "PITA": "Pain In The A..",
    "PRT": "Party",
    "PRW": "Parents Are Watching",
    "QPSA?": "Que Pasa?",
    "ROFL": "Rolling On The Floor Laughing",
    "ROFLOL": "Rolling On The Floor Laughing Out Loud",
    "ROTFLMAO": "Rolling On The Floor Laughing My A.. Off",
    "SK8": "Skate",
    "STATS": "Your sex and age",
    "ASL": "Age, Sex, Location",
    "THX": "Thank You",
    "TTFN": "Ta-Ta For Now!",
    "TTYL": "Talk To You Later",
    "U": "You",
    "U2": "You Too",
    "U4E": "Yours For Ever",
    "WB": "Welcome Back",
    "WTF": "What The F...",
    "WTG": "Way To Go!",
    "WUF": "Where Are You From?",
    "W8": "Wait...",
    "7K": "Sick:-D Laugher",
    "TFW": "That feeling when",
    "MFW": "My face when",
    "MRW": "My reaction when",
    "IFYP": "I feel your pain",
    "TNTL": "Trying not to laugh",
    "JK": "Just kidding",
    "IDC": "I don't care",
    "ILY": "I love you",
    "IMU": "I miss you",
    "ADIH": "Another day in hell",
    "ZZZ": "Sleeping, bored, tired",
    "WYWH": "Wish you were here",
    "TIME": "Tears in my eyes",
    "BAE": "Before anyone else",
    "FIMH": "Forever in my heart",
    "BSAAW": "Big smile and a wink",
    "BWL": "Bursting with laughter",
    "BFF": "Best friends forever",
    "CSL": "Can't stop laughing"
}

# Function
def chat_conversion(text):
    new_text = []
    for i in text.split():
        if i.upper() in chat_words:
            new_text.append(chat_words[i.upper()])
        else:
            new_text.append(i)
    return " ".join(new_text)

nltk.download('stopwords')

# Here we can see all the stopwords in English.However we can chose different Languages also like spanish etc.
stopword = stopwords.words('english')

# Function
def remove_stopwords(text):
    new_text = []

    for word in text.split():
        if word in stopword:
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

# We Will Import WordNetLemmatizer from NLTK Library.
from nltk.stem import WordNetLemmatizer
# Intilize Lemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

def lem_words(word_list):
    wordnet_lemmatizer = WordNetLemmatizer()
    return [wordnet_lemmatizer.lemmatize(word) for word in word_list]

# Complete preprocessing function
def preprocess_text(text):
    text = remove_html_tags(text)
    text = remove_url(text)
    #text = emoji.demojize(text)
    text = remove_punc(text)
    text = chat_conversion(text)
    text = remove_stopwords(text)
    text = word_tokenize(text)
    text = lem_words(text)
    return " ".join(text)

data['text']=data['text'].apply(preprocess_text)

"""#Model

### Load and clean the data
"""

data_train = data.iloc[1:].copy()
x_raw = data_train['text'].astype(str)
y_raw = data_train['Class Index'].astype(int) - 1

"""###Tokenization"""

tokenizer = Tokenizer()
tokenizer.fit_on_texts(x_raw)
x_seq = tokenizer.texts_to_sequences(x_raw)
x_pad = pad_sequences(x_seq, maxlen=200)

"""######Convert to arrays"""

x = np.array(x_pad)
y = np.array(y_raw)

"""### Cross-validation"""

num_folds = 5
batch_size = 300
epochs = 3
vocab_size = len(tokenizer.word_index) + 1
input_length = 200

"""###Model Creation"""

def create_model():
    model = Sequential()
    model.add(Embedding(input_dim=vocab_size, output_dim=128, input_length=input_length))
    model.add(LSTM(units=128, dropout=0.2, recurrent_dropout=0.2))
    model.add(Dense(units=4, activation='softmax'))
    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

from sklearn.model_selection import StratifiedKFold
# Stratified K-Fold
skf = StratifiedKFold(n_splits=num_folds, shuffle=True, random_state=42)
fold_accuracies = []

for fold, (train_idx, val_idx) in enumerate(skf.split(x, y)):
    print(f"\n Fold {fold+1}")
    x_train, x_val = x[train_idx], x[val_idx]
    y_train, y_val = y[train_idx], y[val_idx]

    model = create_model()
    history = model.fit(
        x_train, y_train,
        batch_size=batch_size,
        epochs=epochs,
        validation_data=(x_val, y_val),
        verbose=1
    )
    score = model.evaluate(x_val, y_val, verbose=0)
    print(f"Fold {fold+1} Accuracy: {score[1]:.4f}")
    fold_accuracies.append(score[1])

print(f"\n Average Accuracy over {num_folds} folds: {np.mean(fold_accuracies):.4f}")

"""##Data visualization"""

loss, accuracy = model.evaluate(x_val, y_val)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

# Extract history data
epochs = range(1, len(history.history['accuracy']) + 1)
train_accuracy = history.history['accuracy']
val_accuracy = history.history['val_accuracy']
train_loss = history.history['loss']
val_loss = history.history['val_loss']

# Plot Accuracy
plt.figure(figsize=(10, 5))
plt.plot(epochs, train_accuracy, label='Training Accuracy', color='#1f77b4', marker='o')
plt.plot(epochs, val_accuracy, label='Validation Accuracy', color='#ff7f0e', marker='o')
plt.title('Model Accuracy per Epoch')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)
plt.show()

# Plot Loss
plt.figure(figsize=(10, 5))
plt.plot(epochs, train_loss, label='Training Loss', color='#1f77b4', marker='o')
plt.plot(epochs, val_loss, label='Validation Loss', color='#ff7f0e', marker='o')
plt.title('Model Loss per Epoch')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.show()

from sklearn.metrics import classification_report
import numpy as np

# Generate predictions
# X_test should be padded sequences from tokenizer (e.g., pad_sequences(tokenizer.texts_to_sequences(data['text'])))
# y_test should be your test labels (integer labels 0-3 or one-hot encoded)
y_pred_prob = model.predict(x_val)  # Get probabilities
y_pred = np.argmax(y_pred_prob, axis=1)  # Convert probabilities to class indices

#If y_test is one-hot encoded, convert to class indices
if len(y_val.shape) > 1:  # Check if y_test is one-hot encoded
    y_test = np.argmax(y_val, axis=1)

# Define class names for AG News dataset
class_names = ['World', 'Sports', 'Business', 'Sci/Tech']

# Compute classification report
report = classification_report(y_val, y_pred, target_names=class_names, output_dict=True)

# Extract weighted average metrics
precision = report['weighted avg']['precision']
recall = report['weighted avg']['recall']
f1_score = report['weighted avg']['f1-score']
accuracy = report['accuracy']

# Print metrics
print("Classification Report:")
print(classification_report(y_val, y_pred, target_names=class_names))
print(f"Overall Accuracy: {accuracy:.4f}")
print(f"Weighted Precision: {precision:.4f}")
print(f"Weighted Recall: {recall:.4f}")
print(f"Weighted F1-Score: {f1_score:.4f}")

"""#save model"""

model.save('my_model.keras')

import pickle

with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)